spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "408558233806-cbmpupcotlmpnclq9lvq6hncviotvjpd.apps.googleusercontent.com"
            client-secret: "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"
            redirect-uri: "https://wellness-production-9dcc.up.railway.app/login/oauth2/code/google"
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
