version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/mwellnessydb?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: $idMySQL231

      # If you need to override OAuth2 redirect URI for containers:
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: "http://localhost:8080/login/oauth2/code/google"

    networks:
      - backend-net

  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: $idMySQL231
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-net

volumes:
  mysql-data:

networks:
  backend-net:
    driver: bridge
